version: '3.8'

services:
  i2pd:
    image: purplei2p/i2pd:latest
    container_name: i2pd
    ports:
      - "7070:7070"
      - "4444:4444"
      - "4447:4447"
      - "8080:8080"
    volumes:
      - ./i2pd_data:/home/i2pd/.i2pd
      - ./my-website:/var/www/i2p
    restart: always
