services:
  nginx:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/sites-available:/etc/nginx/sites-available:ro
      - ./config/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./config/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./config/pki:/etc/nginx/pki:ro
    restart: always
    networks:
      - local_network

networks:
  local_network:
    external: true

