global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: ['keycloak:9000']

  - job_name: server
    metrics_path: /metrics
    static_configs:
      - targets: ['${SERVER_IP}:9100']

  - job_name: node-host
    metrics_path: /metrics
    static_configs:
      - targets: ['${HOST_IP}:9100']
